# Ciência de Dados com Python – Cap. 4: NumPy
##  Exercícios Práticos

**Disciplina:** Ciência de Dados com Python (C11)  
**Instituição:** Inatel – Instituto Nacional de Telecomunicações  
**Prof.:** Ruan Patrick de Souza

---

Todos os exercícios utilizam o dataset **`cidades_brasil.csv`**, que contém informações sobre 25 cidades brasileiras.

```
Índice | Coluna      | Descrição
-------|-------------|----------------------------------
  0    | cidade      | Nome da cidade
  1    | estado      | Sigla do estado
  2    | populacao   | População estimada
  3    | area_km2    | Área em km²
  4    | idh         | Índice de Desenvolvimento Humano
  5    | regiao      | Região do Brasil
  6    | fundacao    | Ano de fundação
```

In [4]:
# Importação e carregamento do dataset
import numpy as np

dados = np.loadtxt('cidades_brasil.csv', delimiter=',', dtype=str, skiprows=1)

# Colunas textuais
cidades    = dados[:, 0]
estados    = dados[:, 1]
regioes    = dados[:, 5]

# Colunas numéricas
populacao  = dados[:, 2].astype(int)
area       = dados[:, 3].astype(int)
idh        = dados[:, 4].astype(float)
fundacao   = dados[:, 6].astype(int)

print(f"Dataset carregado: {len(cidades)} cidades")

Dataset carregado: 25 cidades


---
### Exercício 1 – Propriedades e Criação de Arrays

**a)** Exiba as propriedades `size`, `ndim` e `shape` do array `populacao`.

**b)** Crie um array de **zeros** com o mesmo tamanho do array `populacao`. Em seguida, substitua seus valores pela população dividida por **1000** (população em milhares).

**c)** Crie um array usando `np.arange` que represente os **índices** (0, 1, 2, ...) de cada cidade no dataset. Exiba o array.

In [13]:
print(populacao.size)
print(populacao.ndim)
print(populacao.shape)

arr_zeros = np.zeros(populacao.size)
arr_zeros = populacao/1000

print(arr_zeros)

cidades = np.arange(len(cidades))
print(cidades)


25
1
(25,)
[12325.232  6748.     3055.149  2886.698  2703.391  2530.701  2255.903
  1963.726  1661.681  1555.626  1506.42   1492.53   1404.694  1223.237
  1115.932  1025.36    916.001   896.708   871.126   833.932   516.524
   365.855   433.656    44.686    74.824]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


---
### Exercício 2 – Operações Estatísticas

**a)** Calcule e exiba a **média**, o **mínimo** e o **máximo** da população. Mostre também o **nome** da cidade mais populosa e da menos populosa (use `argmax` e `argmin`).

Dica: Caso necessário, para converter dados numéricos que estão como texto no array, você pode fazer a chamada da função `populacao  = dados[:, 2].astype(int)` colocando a tipagem no parêntezes (Ex: `int`, `float`)

**b)** Calcule e exiba a **soma total** das áreas de todas as cidades e a **média** do IDH do dataset.

**c)** Encontre o **índice** da cidade mais antiga (menor ano de fundação) e o **índice** da mais recente. Exiba os nomes e anos correspondentes.

In [71]:
# Resolução do Exercício
media = np.mean(populacao)
minimo = np.min(populacao)
maximo = np.max(populacao)
#mais_populosa = np.argmax(cidades) errado assim 
populacao = dados[:, 2].astype(int)
mais_populosa = cidades[np.argmax(populacao)]
menos_populosa = cidades[np.argmin(populacao)]

idx_antiga = np.argmin(fundacao)
idx_recente = np.argmax(fundacao)

print(cidades[idx_antiga], fundacao[idx_antiga])
print(cidades[idx_recente], fundacao[idx_recente])

print(media)
print(minimo)
print(maximo)
print(mais_populosa)
print(menos_populosa)

8 1537
2 1960
2016303.68
44686
12325232
0
23


---
### Exercício 3 – Operações entre Arrays e Broadcasting

**a)** Calcule a **densidade demográfica** (população / área) de cada cidade e armazene em um novo array. Exiba as 5 cidades com **maior** densidade (exiba nome e valor).

**b)** Calcule a **idade** de cada cidade (2025 - ano de fundação) usando broadcasting. Exiba o array resultante.

**c)** Crie um array de **1's** com o mesmo tamanho que `idh`. Multiplique-o por **1000** e depois **some** com o array `idh * 1000` (IDH em escala de milésimos). Exiba o resultado.

In [33]:
# Resolução do Exercício 3
densidade = populacao / area

indices = np.argsort(densidade)[-5:] 
for i in indices:
    print(cidades[i], densidade[i])

idade_cidades = (2025 - fundacao)
print(idade_cidades)


1 5623.333333333333
8 7622.3899082568805
5 7645.622356495468
0 8103.37409598948
4 8609.525477707006
[471 460  65 476 299 128 356 332 488  92 409 253 465 251 413 210 126 426
 173 440 299 474 479 145 314]


---
### Exercício 4 – Concatenação e Ordenação

**a)** Separe o array `populacao` em dois: um com as **10 primeiras** cidades e outro com as **10 últimas**. Concatene-os em um único array e exiba.

**b)** Ordene o array `idh` em ordem crescente usando `np.sort` e exiba. Qual é o menor e o maior IDH após a ordenação?

**c)** Use `np.argsort` no array `populacao` para obter os **índices** que ordenariam as cidades por população. Exiba os nomes das **5 cidades menos populosas** usando esses índices.

In [58]:
# Resolução do Exercício 4
arr_dez_primeiras = populacao[:10]
#print(arr_dez_primeiras)
arr_dez_ultimas = populacao[-10:]
#print(arr_dez_ultimas)

arr_todos = arr_dez_primeiras + arr_dez_ultimas #isso faz a soma dos paises
#print(arr_todos)

arr_concatenado = np.concatenate((arr_dez_primeiras, arr_dez_ultimas))
print(arr_concatenado)

arr_idh = np.sort(idh)
menor = arr_idh[:1]
print(menor)

cidades_com_menor_populacao = np.argsort(populacao)
print(cidades_com_menor_populacao)

idx_pop = np.argsort(populacao)

for i in idx_pop[:5]:
    print(cidades[i])


[12325232  6748000  3055149  2886698  2703391  2530701  2255903  1963726
  1661681  1555626  1025360   916001   896708   871126   833932   516524
   365855   433656    44686    74824]
[0.721]
[23 24 21 22 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1
  0]
23
24
21
22
20


---
### Exercício 5 – Reshape e Matrizes

**a)** Crie uma **matriz numérica** empilhando `populacao`, `area` e `fundacao` como colunas (use `np.column_stack`). Exiba as propriedades `shape`, `ndim` e `size`.

**b)** Extraia da matriz apenas a **coluna de área** (coluna de índice 1) e exiba.

**c)** Selecione as **5 primeiras linhas** e as **2 primeiras colunas** da matriz (fatiamento). Exiba o resultado e os nomes das cidades correspondentes.

In [ ]:
# Resolução do Exercício 5
matriz = np.column_stack((populacao, area, fundacao))

print(matriz.shape)
print(matriz.ndim)
print(matriz.size)

col_area = matriz[:,1]
print(col_area)

sub = matriz[:5,:2]
print(sub)
print(cidades[:5])



(25, 3)
2
75
[ 1521  1200  5802   693   314   331 11401   435   218   739  1065   497
   318   795   827   510  8093   167  1392   211   675    98   281   350
  1245]
[[12325232     1521]
 [ 6748000     1200]
 [ 3055149     5802]
 [ 2886698      693]
 [ 2703391      314]]
[0 1 2 3 4]
[[12325232     1521     1554]
 [ 6748000     1200     1565]
 [ 3055149     5802     1960]
 [ 2886698      693     1549]
 [ 2703391      314     1726]
 [ 2530701      331     1897]
 [ 2255903    11401     1669]
 [ 1963726      435     1693]
 [ 1661681      218     1537]
 [ 1555626      739     1933]
 [ 1506420     1065     1616]
 [ 1492530      497     1772]
 [ 1404694      318     1560]
 [ 1223237      795     1774]
 [ 1115932      827     1612]
 [ 1025360      510     1815]
 [  916001     8093     1899]
 [  896708      167     1599]
 [  871126     1392     1852]
 [  833932      211     1585]
 [  516524      675     1726]
 [  365855       98     1551]
 [  433656      281     1546]
 [   44686      350     1

---
### Exercício 6 – Fatiamento no Dataset

**a)** Exiba os nomes e populações das cidades de **índice 5 a 9** (5 cidades).

**b)** Exiba os nomes e o IDH das **últimas 3 cidades** do dataset.

**c)** Exiba os dados de todas as cidades **de 2 em 2** (índice 0, 2, 4, ...), mostrando nome e região.

In [ ]:
print(cidades[5:10], populacao[5:10])

print(cidades[-3:], idh[-3:])

print(cidades[::2], regioes[::2])

5 2530701
6 2255903
7 1963726
8 1661681
9 1555626
22 0.84
23 0.721
24 0.741
0 Sudeste
1 Sudeste


---
### Exercício 7 – Filtros Condicionais

**a)** Filtre e exiba os nomes das cidades com **população maior que 2 milhões**.

**b)** Filtre e exiba os nomes das cidades com **IDH maior ou igual a 0.80** que foram **fundadas antes de 1700**.

**c)** Filtre e exiba os nomes das cidades da região **Nordeste** com **área menor que 500 km²**.

In [72]:
print(cidades[populacao > 2000000])

filtro = (idh >= 0.80) & (fundacao < 1700)
print(cidades[filtro])

filtro2 = (regioes == "Nordeste") & (area < 500)
print(cidades[filtro2])

[0 1 2 3 4 5 6]
[ 0  7 21 22]
[ 4  8 17 19]


---
### Exercício 8 – Elementos Únicos e Contagem

**a)** Descubra quais são as **regiões únicas** do dataset e quantas cidades pertencem a cada uma (use `np.unique` com `return_counts=True`).

**b)** Descubra quais são os **estados únicos** e quantas cidades cada estado possui no dataset.

**c)** Exiba qual é a **região com mais cidades** e qual é o **estado com mais cidades** no dataset.

In [ ]:
# Resolução do Exercício 8
reg_unique, reg_counts = np.unique(regioes, return_counts=True)
print(reg_unique, reg_counts)

est_unique, est_counts = np.unique(estados, return_counts=True)
print(est_unique, est_counts)

print(reg_unique[np.argmax(reg_counts)])
print(est_unique[np.argmax(est_counts)])

---
### Exercício 9 – Manipulação de Texto com `np.char`

**a)** Converta todos os nomes de cidades para **letras maiúsculas** e exiba.

**b)** Verifique quais cidades **começam** com a letra `"S"` e exiba seus nomes. Faça o mesmo para cidades que **começam** com `"B"`.

**c)** Encontre o **índice** (posição) da substring `"do"` em cada nome de cidade. Exiba apenas as cidades onde a substring foi encontrada (índice diferente de -1).

In [ ]:
# Resolução do Exercício 9
print(np.char.upper(cidades))

print(cidades[np.char.startswith(cidades, "S")])
print(cidades[np.char.startswith(cidades, "B")])

pos = np.char.find(cidades, "do")

for i in range(len(cidades)):
    if pos[i] != -1:
        print(cidades[i])

---
### Exercício 10 – Persistência de Dados

**a)** Crie uma matriz com as colunas `populacao` e `idh` (use `np.column_stack`). Salve-a em um arquivo de texto **`pop_idh.txt`** usando `np.savetxt` (use `fmt='%.3f'` para manter as casas decimais do IDH).

**b)** Salve o array `fundacao` em um arquivo binário **`fundacao_cidades.npy`** usando `np.save`.

**c)** Carregue ambos os arquivos (`np.loadtxt` e `np.load`) e exiba os dados para confirmar que foram salvos corretamente.

In [ ]:
# Resolução do Exercício 10
mat = np.column_stack((populacao, idh))

np.savetxt("pop_idh.txt", mat, fmt="%.3f")

np.save("fundacao_cidades.npy", fundacao)

dados_txt = np.loadtxt("pop_idh.txt")
dados_npy = np.load("fundacao_cidades.npy")

print(dados_txt)
print(dados_npy)